name: Build Docker

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./CoinSite
          file: ./CoinSite/Dockerfile
          push: true
          tags: orelbaz/action:1.0
  

