name: Build-Test-Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./CoinSite
          file: ./CoinSite/Dockerfile
          push: true
          tags: orelbaz/action:1.0

      - name: Package Helm chart
        run: helm package ./Helm-chart

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: gke-first-393008

      - name: Copy Helm chart to GCS bucket
        run: gsutil cp ./stock-site-0.1.0.tgz gs://stock-action

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: gke-first-393008
      
      - name: Get GKE plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials eks-test --region us-central1-c
      
      - name: Download Helm chart from GCS
        run: |
          gsutil cp gs://stock-action/stock-site-0.1.0.tgz stock-site-0.1.0.tgz

      - name: Deploy Helm chart to test GKE cluster
        run: |
          helm upgrade --install stock-site-test stock-site-0.1.0.tgz